### ISSUE TITLE
Unable to run forked code

### ISSUE THREAD

**Issue by kudlav** [riki95/Many-Time-Pad-Cracker#1]
I forked this repository ran cracker.py with Python 3.7.7 and got the following error:

```
Traceback (most recent call last):
  File "cracker.py", line 54, in <module>
    main()
  File "cracker.py", line 27, in main
    if isSpace(cts,rowCTS[k],k):
  File "cracker.py", line 45, in isSpace
    result = XOR(current,row[coloumn])
  File "cracker.py", line 51, in XOR
    return ord(s1)^ord(s2)
TypeError: ord() expected string of length 1, but int found
```

**Comment by riki95** [comment]
Just passing wrong input file. It expects a different type which is string and you are passing int.

**Comment by kudlav** [comment]
Hi, as I said. I've just forked your repository and ran the code with default ciphertext.txt file. So then you have wrong input file.

Line 51 in XOR should be:
return s1^s2

With this modified line it works (with ciphertext.txt file).

**Comment by riki95** [comment]
Thanks for your fix. I've accepted the pull request.
Really appreciated
